import json
import logging
import os
import shutil
import subprocess
import sys
import xml.etree.ElementTree as Et
from argparse import ArgumentParser, Namespace, RawTextHelpFormatter
from pathlib import Path
from typing import Optional

from fontTools.ttLib import TTFont  # type: ignore

SVG_NS: dict = {"svg": "http://www.w3.org/2000/svg"}

SMUFL_HEADER = """/////////////////////////////////////////////////////////////////////////////
// Name:        smufl.h
// Author:      Laurent Pugin
// Created:     2014-2022
// Copyright (c) Authors and others. All rights reserved.
/////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////
// NOTE: this file was generated by the ./fonts/generate.py smufl script
// and should not be edited because changes will be lost.
/////////////////////////////////////////////////////////////////////////////

#ifndef __VRV_SMUFL_H__
#define __VRV_SMUFL_H__

//----------------------------------------------------------------------------

namespace vrv {{

//----------------------------------------------------------------------------
// SMUFL glyphs available by default in Verovio
//----------------------------------------------------------------------------

enum {{
{smufl_glyph_list}
}};

/** The number of glyphs for verification **/
#define SMUFL_COUNT {len_smufl_codes}

}} // namespace vrv

#endif
"""

FONTFORGE_SCRIPT = (
    """import os; fontforge.open("{input_fontpath}").generate("{output_fontpath}")"""
)

# The sections of the SMuFL metadata used at runtime; the others are derived from the font or unused
RETAINED_METADATA_KEYS = ("fontName", "fontVersion", "engravingDefaults", "glyphsWithAnchors")

log = logging.getLogger(__name__)


def generate_smufl(opts: Namespace) -> bool:
    """
    Generates the `smufl.h` file and the `smufl_names.inc` name table for Verovio.

    :param opts: A set of options from the argument parser sub-command.
    :return: True if successful, False otherwise.
    """
    supported_pth: Path = Path(opts.supported)
    header_out_pth: Path = Path(opts.header_out)
    header_file_pth: Path = Path(header_out_pth, "smufl.h")
    names_file_pth: Path = Path(opts.names_out, "smufl_names.inc")

    if not supported_pth.is_file() or not os.access(supported_pth, os.R_OK):
        log.error("Could not find or read %s file.", supported_pth)
        return False

    if not os.access(header_out_pth, os.W_OK):
        log.error("Could not write to %s.", header_out_pth)
        return False

    log.debug("SMuFL header will be stored in %s", header_out_pth)
    supported_glyphs: dict = __get_supported_glyph_codes(supported_pth)

    fmt_supported_glyphs: list = [
        f"    SMUFL_{gcode}_{gname} = 0x{gcode}," for gcode, gname in supported_glyphs.items()
    ]

    log.debug("SMuFL header will contain %s supported glyphs", len(fmt_supported_glyphs))
    fmt_glyph_list = "\n".join(fmt_supported_glyphs)
    fmt_header = SMUFL_HEADER.format(
        smufl_glyph_list=fmt_glyph_list, len_smufl_codes=len(fmt_supported_glyphs)
    )

    log.debug("Writing %s", header_file_pth)
    with open(header_file_pth, "w") as header_inc:
        header_inc.write(fmt_header)

    log.debug("Finished writing SMuFL header")

    log.debug("Writing %s", names_file_pth)
    with open(names_file_pth, "w", encoding="utf-8") as names_inc:
        names_inc.write("// Generated by fonts/generate.py smufl; do not edit.\n")
        for gcode, gname in sorted(supported_glyphs.items(), key=lambda item: int(item[0], 16)):
            names_inc.write(f"{{ U'\\U{int(gcode, 16):08X}', \"{gname}\" }},\n")

    log.debug("Finished writing SMuFL name table")
    return True


def bundle_font(opts: Namespace) -> bool:
    """
    Creates the runtime files of a font bundled with Verovio: the WOFF2 font and its compacted SMuFL metadata.

    The WOFF2 font of the source directory is used when available. Otherwise, the OTF or TTF font is
    losslessly converted to WOFF2.

    :param opts: A set of options from the argument parser sub-command.
    :return: True if successful, False otherwise.
    """
    fontname: str = opts.fontname

    font_data_pth: Path = Path(opts.source, fontname)
    metadata_pth: Path = Path(font_data_pth, f"{fontname.lower()}_metadata.json")
    fonts_pth: Path = Path(opts.data, "fonts")
    woff2_out_pth: Path = Path(fonts_pth, f"{fontname}.woff2")
    metadata_out_pth: Path = Path(fonts_pth, f"{fontname}_metadata.json")

    if not os.access(fonts_pth, os.W_OK):
        log.error("Could not write to %s. Check permissions.", fonts_pth)
        return False

    candidates: list[Path] = [
        Path(font_data_pth, f"{fontname}.{ext}") for ext in ("woff2", "otf", "ttf")
    ]
    font_pth: Optional[Path] = next((c for c in candidates if os.access(c, os.R_OK)), None)
    if not font_pth:
        log.error("Could not find a WOFF2, OTF, or TTF font for %s in %s", fontname, font_data_pth)
        return False

    if font_pth.suffix == ".woff2":
        log.debug("Copying %s to %s", font_pth, woff2_out_pth)
        shutil.copyfile(font_pth, woff2_out_pth)
    else:
        log.debug("Converting %s to %s", font_pth, woff2_out_pth)
        # Keep the timestamp of the source for a deterministic output
        font = TTFont(str(font_pth), recalcTimestamp=False)
        font.flavor = "woff2"
        font.save(str(woff2_out_pth))

    if not os.access(metadata_pth, os.R_OK):
        log.error("Could not read %s. Does it exist?", metadata_pth)
        return False

    with open(metadata_pth, "r", encoding="utf-8") as jfile:
        metadata: dict = json.load(jfile)

    missing: list[str] = [key for key in RETAINED_METADATA_KEYS if key not in metadata]
    if missing:
        log.error("The metadata %s is missing required keys: %s", metadata_pth, ", ".join(missing))
        return False

    compact: dict = {key: metadata[key] for key in RETAINED_METADATA_KEYS}
    log.debug("Writing %s", metadata_out_pth)
    with open(metadata_out_pth, "w", encoding="utf-8") as jfile:
        jfile.write(json.dumps(compact, ensure_ascii=False, separators=(",", ":")) + "\n")

    return True


def generate_svg(opts: Namespace) -> bool:
    """
    Generates a SVG font file from an input file using Fontforge.

    :param opts: A set of options from the argument parser sub-command.
    :return: True if successful, False otherwise.
    """
    convert_res: bool = __fontforge_convert(opts, "svg")
    if not convert_res:
        log.error("A problem happened with the fontforge conversion to SVG.")
        return False

    return True


def generate_woff2(opts: Namespace) -> bool:
    """
    Generates a WOFF2 file using Fontforge

    :param opts: A set of options from the argument parser sub-command.
    :return: True if successful, False otherwise.
    """
    convert_res: bool = __fontforge_convert(opts, "woff2")
    if not convert_res:
        log.error("A problem happened with the fontforge conversion to WOFF2.")
        return False

    return True


def check(opts: Namespace) -> bool:
    """
    Checks the glyphs of a font against the list of supported glyphs and identifies any glyphs
    that are missing in the font.

    :param opts: A set of options from the argument parser sub-command
    :return: True if successful, False otherwise
    """
    fontname: str = opts.fontname

    source_pth: Path = Path(opts.source)
    font_data_pth: Path = Path(source_pth, fontname)
    font_pth: Path = Path(font_data_pth, f"{fontname}.svg")

    all_glyphs: dict = __combine_alternates_and_supported(opts)

    Et.register_namespace("", SVG_NS["svg"])
    svg_font: Et.ElementTree = Et.parse(str(font_pth))
    glyphs: list[Et.Element] = svg_font.findall(".//svg:glyph", SVG_NS)
    glyph_names: list[str] = []
    for g in glyphs:
        if g is not None and (gn := g.get("glyph-name")):
            # space is not given as octal in svg fonts
            if gn == "space":
                gn = "0020"
            glyph_names.append(gn[-4:] if gn.startswith("uni") else gn)

    supported_codes: set = set(all_glyphs.keys())
    font_codes: set = set(glyph_names)

    supported_codes_not_in_font: set = supported_codes.difference(font_codes)
    font_codes_not_in_supported: set = font_codes.difference(supported_codes)

    sc: list[str] = sorted(list(supported_codes_not_in_font))
    fc: list[str] = sorted(list(font_codes_not_in_supported))
    print(f"Verovio-supported glyphs not in {fontname}: ", ", ".join(sc))
    if opts.show_unsupported:
        print(f"{fontname} glyphs not supported by Verovio: ", ", ".join(fc))

    return True


#########
# Private implementation methods.
#########
def __combine_alternates_and_supported(opts) -> dict:
    fontname: str = opts.fontname
    source_pth: Path = Path(opts.source)
    font_data_pth: Path = Path(source_pth, fontname)
    metadata_pth: Path = Path(font_data_pth, f"{fontname.lower()}_metadata.json")
    supported_glyphs: dict = __get_supported_glyph_codes(opts.supported)

    with open(metadata_pth, "r") as jsonfile:
        metadata: dict = json.load(jsonfile)

    if not os.access(metadata_pth, os.R_OK):
        log.warning("The metadata file could not be read at %s", metadata_pth)
        return supported_glyphs

    alternate_glyphs: dict = __get_alternate_glyphs(supported_glyphs, metadata)

    if alternate_glyphs:
        log.debug("Updating supported glyphs with alternates")
        supported_glyphs.update(alternate_glyphs)

    return supported_glyphs


def __check_fontforge(opts: Namespace) -> Optional[str]:
    fontforge_path: Optional[str] = (
        shutil.which("fontforge") if not opts.fontforge else opts.fontforge
    )
    if fontforge_path is None:
        log.error("Could not find fontforge. It is required for this operation.")
        return None

    if not os.access(fontforge_path, os.X_OK):
        log.error("%s does not point to an executable.", fontforge_path)
        return None

    log.debug("Found fontforge at %s", fontforge_path)
    return fontforge_path


def __fontforge_convert(opts: Namespace, fmt: str) -> bool:
    if fmt not in ("svg", "woff2"):
        log.error("Unknown conversion format %s. Must be either 'svg' or 'woff2'.", fmt)
        return False

    fontforge_path: Optional[str] = __check_fontforge(opts)
    if not fontforge_path:
        return False

    fontname: str = opts.fontname
    font_pth: Path = Path(opts.fontfile)

    if not font_pth.is_file() or not os.access(font_pth, os.R_OK):
        log.error("Could not find or read %s.", font_pth)
        return False

    subprocess_environment: dict = os.environ.copy()
    subprocess_environment["SOURCE_DATE_EPOCH"] = str(int(font_pth.stat().st_mtime))

    fontforge_cmd: list = [fontforge_path, "-lang=py", "-"]

    output_fontname: Path = Path(font_pth.parent, f"{fontname}.{fmt}")

    ff_script: bytes = FONTFORGE_SCRIPT.format(
        input_fontpath=str(font_pth), output_fontpath=str(output_fontname)
    ).encode()

    try:
        _: subprocess.CompletedProcess = subprocess.run(
            fontforge_cmd, input=ff_script, check=True, env=subprocess_environment
        )
    except subprocess.CalledProcessError as e:
        log.error(
            "Fontforge exited with an error. Command: %s, Code: %s, Output: %s",
            e.cmd,
            e.returncode,
            e.output,
        )
        return False

    log.debug("Converted %s to %s", font_pth.resolve(), output_fontname.resolve())
    return True


def __get_supported_glyph_codes(supported: Path) -> dict:
    """Retrieve dictionary with supported SMuFL codepoints and name."""
    log.debug("Getting supported glyph codes from %s", supported)
    supported_xml = Et.parse(str(supported))
    glyphs: list[Et.Element] = supported_xml.findall(".//glyph")

    log.debug("Found %s supported glyphs", len(glyphs))
    return {g.attrib["glyph-code"]: g.attrib["smufl-name"] for g in glyphs}


def __get_alternate_glyphs(glyphs: dict, metadata: dict) -> dict:
    glyph_alternates: dict = metadata.get("glyphsWithAlternates", {})
    inverted_glyphs: dict = {v: k for k, v in glyphs.items()}
    additional_glyphs: dict = {}

    for name, alternates in glyph_alternates.items():
        code: Optional[str] = inverted_glyphs.get(name)
        if not code:
            continue

        for alt in alternates["alternates"]:
            additional_glyphs[alt["codepoint"][2:]] = alt["name"]

    log.debug("Found %s alternate glyphs", len(additional_glyphs.keys()))
    return additional_glyphs


if __name__ == "__main__":
    cli = ArgumentParser()
    cli.add_argument("--debug", help="Run the command with debug output.", action="store_true")
    subparsers = cli.add_subparsers(help="[sub-command] help")
    supported_xml_help: str = "Path to a supported.xml file"
    smufl_description = """
    Creates the SMuFL header file and the SMuFL name table for Verovio from the supported glyphs.
    """
    parser_smufl = subparsers.add_parser("smufl", description=smufl_description)
    parser_smufl.add_argument("--supported", help=supported_xml_help, default="./supported.xml")
    parser_smufl.add_argument("--header-out", default="../include/vrv/")
    parser_smufl.add_argument("--names-out", default="../src/")
    parser_smufl.set_defaults(func=generate_smufl)

    fontname_help = "The name of the font, which is also the name of its source directory."
    bundle_description = """
    Creates the WOFF2 font and the compacted SMuFL metadata of a font bundled with Verovio in the data
    directory, from the WOFF2, OTF, or TTF font and the SMuFL metadata of its source directory.
    """
    parser_bundle = subparsers.add_parser("bundle", description=bundle_description)
    parser_bundle.add_argument("fontname", help=fontname_help)
    parser_bundle.add_argument(
        "--data", help="Path to the Verovio data directory", default="../data"
    )
    parser_bundle.add_argument("--source", help="The font source parent directory", default="./")
    parser_bundle.set_defaults(func=bundle_font)

    svg_description = """
    Creates an SVG font from any other font file supported by fontforge.
    """
    parser_svg = subparsers.add_parser("svg", description=svg_description)
    parser_svg.add_argument(
        "fontname",
        help="The name of the font. SVG files will be generated with this name",
    )
    parser_svg.add_argument(
        "fontfile",
        help="The path to the source font file. Can be any font file supported by fontforge.",
    )
    parser_svg.add_argument(
        "--fontforge",
        help="Path to fontforge binary (default is to auto-detect on the path)",
        default=None,
    )
    parser_svg.set_defaults(func=generate_svg)

    woff2_description = """
    Creates a WOFF2 font from any other font file supported by fontforge.
    """
    parser_woff2 = subparsers.add_parser("woff2", description=woff2_description)
    parser_woff2.add_argument(
        "fontname",
        help="The name of the font. SVG files will be generated with this name",
    )
    parser_woff2.add_argument(
        "fontfile",
        help="The path to the source font file. Can be any font file supported by fontforge.",
    )
    parser_woff2.add_argument(
        "--fontforge",
        help="Path to fontforge binary (default is to auto-detect on the path)",
        default=None,
    )
    parser_woff2.set_defaults(func=generate_woff2)

    check_description: str = """
    Checks the supported.xml file against a specified font, and reports on the glyphs that are supported
    by Verovio, but that are not in that font.
    
    Optionally, with the use of the `--show-unsupported` flag, will also show the list of glyphs that are in
    the font that are not supported by Verovio.
    """
    unsupported_help: str = (
        "Also show a list of glyphs in the font that are not supported by Verovio."
    )
    parser_check = subparsers.add_parser(
        "check", description=check_description, formatter_class=RawTextHelpFormatter
    )
    parser_check.add_argument("fontname", help=fontname_help)
    parser_check.add_argument("--supported", help=supported_xml_help, default="./supported.xml")
    parser_check.add_argument("--source", help="The font source parent directory", default="./")
    parser_check.add_argument("--show-unsupported", help=unsupported_help, action="store_true")

    parser_check.set_defaults(func=check)

    cmd_opts: Namespace = cli.parse_args()

    if cmd_opts.debug:
        LOGLEVEL = logging.DEBUG
    else:
        LOGLEVEL = logging.WARNING

    logging.basicConfig(
        format="[%(asctime)s] [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)",
        level=LOGLEVEL,
    )

    res: bool = cmd_opts.func(cmd_opts)

    if not res:
        log.error("An error has occurred.")
        sys.exit(1)

    sys.exit(0)
