#!/usr/bin/env python3
"""Generate the compact runtime SMuFL name/code table from supported.xml."""

from pathlib import Path
from xml.etree import ElementTree


root = Path(__file__).resolve().parent
glyphs = []
for element in ElementTree.parse(root / "supported.xml").iter("glyph"):
    code = element.get("glyph-code")
    name = element.get("smufl-name")
    if code and name:
        glyphs.append((int(code, 16), name))
glyphs.sort()

output = root.parent / "src" / "smufl_names.inc"
with output.open("w", encoding="utf-8") as stream:
    stream.write("// Generated by fonts/generate-smufl-name-table.py; do not edit.\n")
    for code, name in glyphs:
        stream.write(f'{{ U\'\\U{code:08X}\', "{name}" }},\n')
